language: go
go:
  - 1.14.x

os:
  - linux

git:
  depth: 3

services: mysql
before_install:
  - mysql -e "CREATE DATABASE IF NOT EXISTS test;"
env:
  - DB_HOST=127.0.0.1 DB_PORT=3306 DB_NAME=test DB_USER=root

gobuild_args: -v -race